import worker from '../../../test-worker.js';
import './accepts.spec.js';
import './application.spec.js';
import './context.spec.js';
import './cookies.spec.js';
import './http-error.spec.js';
import './normalize-pathname.spec.js';
import './req.spec.js';
import './response-builder.spec.js';
import './validate.spec.js';
import './router.spec.js';
export default worker;
